### ISSUE TITLE
install services in the hub project sdk directory

### ISSUE THREAD

**Issue by piot** [coherence/hub-server#2]
gRPC command that uses the global installer to install a specific version.

Install is basically copying executables from the global installer cache to the project sdk directory.

**Comment by gamedolphin** [comment]
Installer is now packaged as an executable and is called directly by the sdk (through a c# process) by running the executable directly. GRPC commands are not used to run the installer. The installer exposes a path argument which allows it to install to a specific directory, and in the case of the sdk, the path is the local sdk project.
